application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      database-storage-example:
        license: Apache-2.0
        actions:
          create:
            function: actions/generic/create.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          list:
            function: actions/generic/list.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              include-ims-credentials: true
              final: true
          update:
            function: actions/generic/update.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          delete:
            function: actions/generic/delete.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          find:
            function: actions/generic/find.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          publish-events:
            function: actions/publish-events/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              require-adobe-auth: true
              final: true
    database:
      auto-provision: false
      region: amer
